name: Scraping PBH using R

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::xml2
            any::rvest
      - name: Generating table
        run: |-
          Rscript "scrape_pbh.R"
      - name: Commit e Push
        run: |-
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Atualizado (pelo R) em: ${timestamp}" || exit 0
          git push
